// AUTO-GENERATED by scripts/generate-build-meta.mjs — do not edit.
export const APP_BUILD_ID = "local-mpcec02l";
export const APP_BUILD_TIME = "2026-05-19T08:53:57.213Z";
export const NAV_CONFIG_VERSION = "2";
