// AUTO-GENERATED by scripts/generate-build-meta.mjs — do not edit.
export const APP_BUILD_ID = "local-mpbd1cd5";
export const APP_BUILD_TIME = "2026-05-18T15:29:54.136Z";
export const NAV_CONFIG_VERSION = "2";
